export const PDF_FAQS = [
  ["What file types can I convert to PDF?", "You can convert images (JPG, PNG, GIF, BMP, WebP, SVG) and text files (TXT, HTML) into a PDF. Each file becomes a page in the final document."],
  ["Is this PDF maker free?", "Yes. Everything runs in your browser for free. There is no signup, no watermark and no file size limit."],
  ["Are my files uploaded to a server?", "No. All processing happens in your browser. Your files never leave your device, and nothing is stored on our servers."],
  ["Can I reorder pages?", "Yes. After uploading, use the arrow buttons to move files up or down. The order you set is the page order in the PDF."],
  ["What page sizes are available?", "A4, US Letter and Legal. You can also choose portrait or landscape orientation and adjust margins from none to large."],
];

export const PDF_GUIDES = {
  "how-to-convert-images-to-pdf": {
    title: "How to Convert Images to PDF (Free, No Upload)",
    description: "Step-by-step guide to combining JPG, PNG and other images into a single PDF using a free browser-based tool, with tips on page size, order and quality.",
    h1: "How to Convert Images to PDF",
    date: "2026-10-04",
    sections: [
      { h: "Why convert images to PDF?", p: ["A PDF keeps multiple images in a fixed layout that looks the same on every device and printer. Sending five separate JPG files risks them arriving out of order, being resized by a messaging app or losing quality when forwarded. One PDF bundles them in the sequence you chose, with the page size and orientation you picked.", "Common reasons to convert images to PDF include submitting scanned documents, compiling receipts or invoices, preparing a photo portfolio for print, and combining screenshots into a single report."] },
      { h: "Steps to convert images to PDF", p: ["Open the PDF maker and click the upload area. Select the images you want to include — JPG, PNG, GIF, BMP, WebP and SVG are all supported. You can select multiple files at once.", "After uploading, use the arrow buttons to reorder pages. The order in the list is the order in the final PDF. Remove any file you added by mistake.", "Choose a page size (A4, Letter or Legal), orientation (portrait or landscape) and margin setting. For photos that should fill the page, set margins to none. For documents that will be printed and stapled, normal or large margins leave room for binding.", "Click Generate. Your browser opens a print preview with all the images laid out. Choose 'Save as PDF' in the print dialog to save the file. On Chrome this option is in the destination dropdown; on Safari it is in the bottom-left PDF menu."] },
      { h: "Getting the best results", p: ["Use the highest resolution images you have. The tool does not compress your files — what you upload is what goes into the PDF. A 300 DPI image printed at A4 size needs to be at least 2480 by 3508 pixels for sharp output.", "If your images are a mix of portrait and landscape, choose the orientation that suits the majority, or split them into two PDFs. A landscape photo on a portrait page will be shrunk to fit the width, leaving blank space above and below.", "SVG files are ideal for logos, diagrams and illustrations because they scale to any page size without losing sharpness. Use PNG or JPG for photographs."] },
      { h: "Privacy and file size", p: ["The conversion runs entirely in your browser. Your images are never uploaded to a server, which means there is no file size limit imposed by us and no risk of your files being stored or seen by anyone else. Close the tab and everything is gone.", "The final PDF size depends on the images inside it. A ten-page PDF of phone photos will typically be 10 to 30 MB. If you need a smaller file, resize your images before uploading or use your operating system's built-in PDF compression after saving."] },
    ],
  },
  "how-to-merge-files-into-one-pdf": {
    title: "How to Merge Files Into One PDF (Free, In Your Browser)",
    description: "How to combine several images and text files into a single PDF in the order you want, what can and cannot be merged, and what to check before you send it.",
    h1: "How to Merge Files Into One PDF",
    date: "2026-10-04",
    sections: [
      { h: "What you can merge", p: ["The PDF maker combines images (JPG, PNG, GIF, BMP, WebP, SVG) and text files (TXT, HTML) into one document. You can mix types in the same PDF: for example a cover note saved as a TXT file, followed by scanned pages as JPGs and a chart as a PNG.", "Each image gets its own page. A text file is laid out as plain text and runs onto as many pages as it needs, with long lines wrapped to fit the page width."] },
      { h: "Steps to merge files into one PDF", p: ["Open the PDF maker and select your files. You can pick several at once, and you can add more afterwards; new files are appended to the end of the list rather than replacing what is already there.", "Put the files in order with the arrow buttons. The list order is the page order, so check it from top to bottom before you continue. Remove anything you added by mistake.", "Choose the page size (A4, Letter or Legal), orientation and margins. These settings apply to the whole document, not to individual pages.", "Click Generate, then choose 'Save as PDF' in the print dialog that opens. The preview in that dialog shows the page count and exactly how each page will look, so it is the best place to catch a problem before saving."] },
      { h: "Getting order and layout right", p: ["If you have many files, rename them with numbered prefixes (01-cover, 02-invoice, 03-receipt) before selecting them. Numbered names sort into the right sequence in your file picker and make a missing or misplaced page easy to spot in the list.", "Because one orientation applies to every page, a document that is mostly portrait with one wide table or landscape photo will show that page shrunk to fit the width. If that page matters, rotate the image before adding it, or make it a separate landscape PDF.", "Margins are a trade-off. 'None' lets scans and photos fill the page but most home printers cannot print right to the edge, so content near the border may be cut off on paper. Normal margins are the safer choice for anything that will be printed."] },
      { h: "What this tool does not merge", p: ["The tool builds a new PDF from images and text. It does not accept existing PDF files, Word documents or spreadsheets as input. To include a Word or Excel file, export the pages you need as images, or take screenshots, and add those.", "To join PDFs that already exist, use a dedicated PDF merger. On a Mac, the built-in Preview app can do this by dragging pages between the thumbnail sidebars of two open PDFs."] },
      { h: "Check the result before you send it", p: ["Open the saved PDF and scroll through every page. Confirm the page count matches what you expected, nothing is cut off at the edges and small text in scans is still readable when you zoom to 100%.", "Everything happens in your browser. Your files are not uploaded, there is no signup and no watermark is added, so the merged PDF contains only what you put into it."] },
    ],
  },
  "pdf-page-size-guide": {
    title: "PDF Page Size Guide: A4 vs Letter vs Legal",
    description: "Exact dimensions of A4, US Letter and Legal pages, which one to choose for printing or submitting a PDF, and how many pixels your images need to look sharp.",
    h1: "PDF Page Size Guide: A4, Letter and Legal",
    date: "2026-10-09",
    sections: [
      { h: "The three common page sizes", p: ["A4 is 210 by 297 mm (8.27 by 11.69 inches). It is the standard paper size in India, Europe, Australia and most of the world, and it is what most offices, schools and government portals outside North America expect.", "US Letter is 8.5 by 11 inches (216 by 279 mm). It is the default in the United States and Canada. Compared with A4 it is about 6 mm wider and 18 mm shorter.", "Legal is 8.5 by 14 inches (216 by 356 mm): the same width as Letter but noticeably taller. It is used mainly in North America for contracts and some forms, and is rarely asked for elsewhere."] },
      { h: "Which size should you pick?", p: ["Match the paper the reader will print on. If you are sending a document to someone in the US or Canada, use Letter; for almost everyone else, use A4. If a form, portal or teacher names a size, use exactly that.", "When in doubt, A4 is the safer choice for an international audience. Printers set to Letter will usually scale an A4 page down slightly to fit, and the reverse also works, but scaling can push content close to the edge or make small text smaller than intended.", "Choose Legal only when someone specifically asks for it. A Legal page printed on A4 or Letter paper is shrunk noticeably to fit the extra height."] },
      { h: "Image resolution for each size", p: ["Print quality depends on how many pixels cover each inch of paper. 300 pixels per inch (DPI) gives sharp results for photos and scanned text; 150 DPI is acceptable for documents that will mostly be read on screen.", "For a full page with no margins at 300 DPI you need roughly 2480 by 3508 pixels for A4, 2550 by 3300 for Letter and 2550 by 4200 for Legal. At 150 DPI, halve those numbers. A typical phone photo of 3000 by 4000 pixels is enough for a sharp A4 or Letter page.", "Upscaling a small image does not add detail. If a screenshot or old scan is only 800 pixels wide, it will look soft on a full page no matter which size you pick, so it is better to leave it smaller with margins around it."] },
      { h: "Orientation and margins", p: ["Portrait suits documents, forms and most phone photos. Landscape suits wide tables, slides, charts and horizontal photos. In the PDF maker one orientation applies to the whole document, so if only one page is wide, rotate that image before adding it.", "Most home and office printers cannot print to the very edge of the paper. If you set margins to none, anything within a few millimetres of the border may be cut off on paper. Keep normal margins for anything that will be printed, and use no margins for PDFs meant only for screens."] },
      { h: "Setting the page size in the PDF maker", p: ["Upload your images or text files, then choose A4, Letter or Legal, plus orientation and margins, before clicking Generate. The print dialog that opens shows a preview of every page at the chosen size, which is the easiest place to spot a page that is too small or cut off.", "If the print dialog also has its own paper size or scaling option, keep it consistent with the size you picked, and use 'Default' or '100%' scaling so pages are not resized a second time. The tool is free, runs in your browser and does not upload your files."] },
    ],
  },
};
