export const VCF_FAQS = [
  ["What is a VCF file?", "A VCF (vCard File) is a standard format for storing contact information. It lets you save multiple contacts in one file and import them all at once into any phone or email app."],
  ["Is this VCF maker free?", "Yes. It runs entirely in your browser. There is no signup, no upload to our servers and no limit on the number of contacts."],
  ["Which devices can import a VCF file?", "Android, iPhone, Gmail, Outlook and most contact apps support VCF import. Tap the file on your phone and it offers to add all contacts at once."],
  ["What does the name prefix tag do?", "It adds a short label before every contact name, such as 'g. Rahul Sharma'. This helps you search and filter imported contacts later."],
  ["Can I add contacts without a CSV?", "Yes. Click 'Add Contacts Manually' and type each contact directly in the table. You can also mix both methods."],
];

export const VCF_GUIDES = {
  "what-is-a-vcf-file": {
    title: "What Is a VCF File? How It Works and How to Use One",
    description: "Learn what a VCF (vCard) file is, what it stores, how to open and import one on Android and iPhone, and when to use it over a spreadsheet.",
    h1: "What Is a VCF File?",
    date: "2026-10-04",
    sections: [
      { h: "VCF basics", p: ["VCF stands for vCard File. It is a plain-text file format (file extension .vcf) that stores contact information — name, phone number, email, company, address and more — in a standard structure that every major phone, email client and contacts app can read.", "The format was introduced in the mid-1990s and is now maintained as an open standard (RFC 6350). Because it is universally supported, a VCF file created on an Android phone opens just as well on an iPhone, in Gmail, in Outlook or in Thunderbird."] },
      { h: "What a VCF file contains", p: ["Each contact in a VCF file is wrapped between BEGIN:VCARD and END:VCARD lines. Inside, fields like FN (full name), TEL (phone), EMAIL, ORG (organisation) and NOTE hold the data. A single .vcf file can contain one contact or thousands — the file simply stacks the vCard blocks one after another.", "The format supports version 3.0 and 4.0. Version 3.0 is the most widely compatible and is what most tools, including ours, produce. It covers the fields most people need: name, phone, email, company, categories and notes."] },
      { h: "How to open and import a VCF file", p: ["On Android, tap the downloaded .vcf file. The Contacts app opens and offers to import all contacts at once. You can choose which account (Google, phone, SIM) to save them to. Alternatively, open Google Contacts, tap the menu, choose Import, and select the file.", "On iPhone, open the .vcf file from Mail, AirDrop, Files or a messaging app. iOS shows a preview and an 'Add All Contacts' button at the top. Tap it, confirm, and the contacts appear in your address book.", "On a computer, double-clicking a .vcf file usually opens it in the default contacts or mail app. You can also import it manually into Gmail (Contacts > Import) or Outlook (File > Open & Export > Import/Export)."] },
      { h: "VCF vs CSV for contacts", p: ["A CSV (comma-separated values) file is a spreadsheet format. It is easy to edit in Excel or Google Sheets but has no standard field mapping — one app's 'Mobile Phone' column might be another's 'Cell'. Importing a CSV often means manually matching columns.", "A VCF file uses named fields that every contacts app already understands, so there is no column-mapping step. The trade-off is that VCF is harder to edit by hand. The practical workflow is: prepare your contacts in a spreadsheet (CSV), then convert to VCF for importing."] },
      { h: "When to use a VCF file", p: ["Use VCF whenever you need to move contacts between devices or share a contact list with other people. Teachers sharing parent contacts, event organisers distributing attendee lists, sales teams handing over leads, and businesses onboarding new staff all benefit from a single .vcf file that imports in one tap.", "Our VCF maker takes a CSV of contacts, lets you preview and edit them, adds an optional name prefix tag for easy searching, and downloads a ready-to-import .vcf file. Everything runs in your browser — your contacts are never uploaded to a server."] },
    ],
  },
  "how-to-import-contacts-on-android": {
    title: "How to Import Contacts on Android from a VCF File",
    description: "Step-by-step guide to importing a .vcf contacts file on Android: using the Contacts app, Google Contacts, choosing an account, and fixing common problems.",
    h1: "How to Import Contacts on Android",
    date: "2026-10-05",
    sections: [
      { h: "Before you start", p: ["You need a .vcf file on your phone. It can arrive by email, WhatsApp, Google Drive, USB transfer or a direct browser download. If you are building the file yourself, our VCF maker produces a standard version 3.0 vCard that Android reads without any conversion.", "Decide where the contacts should live. Saving to your Google account means they sync to every device you sign in to and survive a lost phone. Saving to Phone keeps them on this device only, and SIM storage holds just a name and one number per entry."] },
      { h: "Method 1: Open the file directly", p: ["Tap the downloaded .vcf file from your Files app, Downloads or the email attachment. Android usually hands it to the Contacts app, which asks which account to save to and then imports every contact in the file in one go.", "If tapping the file does nothing, open the Files app, long-press the .vcf file, choose Open with, and pick Contacts. Some phones show the file as unknown until you do this once."] },
      { h: "Method 2: Import from inside Contacts", p: ["Open the Contacts app (or Google Contacts), tap the menu, then Settings or Fix & manage, and choose Import. Select .vcf file, browse to the file, and pick the destination account. The wording differs slightly between Samsung, Pixel, Xiaomi and other phones, but the Import option is always in the same menu area.", "You can also import on a computer: sign in at contacts.google.com, choose Import, and upload the .vcf file. The contacts then sync to your phone automatically, which is handy for very large lists."] },
      { h: "Check the result and fix problems", p: ["Search for one or two names to confirm they arrived. If you used a name prefix tag when creating the file, searching for that prefix lists the whole batch, which also makes it easy to select and delete them if something went wrong.", "If contacts appear twice, use Merge and fix in Google Contacts to combine duplicates. If nothing imports, check that the file really ends in .vcf and not .txt, and that it begins with BEGIN:VCARD when opened in a text editor. Accented or non-English names are fine because the file is saved as UTF-8."] },
      { h: "Tips for large or shared lists", p: ["Android handles thousands of contacts in one file, but importing may take a minute, so let it finish before leaving the screen. If you share a list with a group, tell recipients to pick the same destination account type so the contacts end up where they expect.", "Our VCF maker runs in your browser, needs no signup, adds no watermark and does not upload your contact data anywhere, so it is safe to use for lists containing personal numbers."] },
    ],
  },
};
